services:
    web:
        build:
            context: .
        ports:
            - '3000:3000'
        env_file: ./config/.env
        volumes:
            - ./:/app
            # - /app/node_modules
        command: 'npm run dev-server'
    db:
        env_file: ./config/.env
        image: postgres:latest
        ports:
            - '5432:5432'
