name: Trigger Heroku to wake up 

on: 
    schedule:
        - cron: "*/10 * * * *"

jobs:
    trigger-heroku:
        runs-on: ubuntu-latest
        steps:
            - name: trigger sever
              run: curl https://helpmehelpyou.herokuapp.com/

